name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  source-github-username:
    description: 'Source repository'
    required: true
  source-repository-name:
    description: 'Name of the source username/organization'
    required: true
  source-branch-name:
    description: '[Optional] set target branch name for the source repository. Defaults to "master"'
    required: false
    default: 'master'
  destination-github-username:
    description: 'Name of the destination username/organization'
    required: true
  destination-repository-name:
    description: 'Destination repository'
    required: true
  destination-branch-name:
    description: '[Optional] set target branch name for the destination repository. Defaults to "master"'
    required: false
    default: 'master'
  user-email:
    description: 'Email for the git commit'
    required: true
  user-name:
    description: 'Email for the git commit'
    required: true
  commit-message:
    description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
    default: 'Update from ORIGIN_COMMIT'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-github-username }}
    - ${{ inputs.source-repository-name }}
    - ${{ inputs.source-branch-name }}
    - ${{ inputs.destination-github-username }}
    - ${{ inputs.destination-repository-name }}
    - ${{ inputs.destination-branch-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.commit-message }}
branding:
  icon: 'git-commit'
  color: 'green'